Fix/modul cabang
aribowobob/pos-fe pull request #18
Opened 2024-08-12 08:45 UTC by dionrespati

2024-08-13 04:30 UTC, aribowobob requested changes

2024-08-13 06:31 UTC, dionrespati commented on src/modules/system/product/form-product.tsx
> +  const [isEditForm, setIsEditForm] = useState(false);
FIXED

2024-08-13 06:31 UTC, dionrespati commented on src/modules/system/product/form-product.tsx
> +    if (id === 0 || id === undefined || id === null) {
FIXED

2024-08-13 06:32 UTC, dionrespati commented on src/modules/system/product/form-product.tsx
> +                className="w-1/4"
FIXED

2024-08-13 06:32 UTC, dionrespati commented on src/modules/system/product/form-product.tsx
> +              <Button className="w-3/4" onClick={() => handleSubmit()}>
FIXED

2024-08-13 06:33 UTC, dionrespati commented on src/modules/system/product/form-product.tsx
> +            <Button className="w-full" onClick={() => handleSubmit()}>
FIXED

2024-08-14 04:44 UTC, aribowobob approved these changes

2024-08-15 08:12 UTC, merged